export const rows = [
  {
    id: 1,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Tax Sale',
    status: 'Paid',
  },
  {
    id: 2,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Adjudicated/Active',
    status: 'Unpaid',
  },
  {
    id: 3,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Real Estate',
    status: 'Paid',
  },
  {
    id: 4,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Adjudicated/Active',
    status: 'Paid',
  },
  {
    id: 5,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Real Estate',
    status: 'Paid',
  },
  {
    id: 6,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Adjudicated/Active',
    status: 'Paid',
  },
  {
    id: 7,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Real Estate',
    status: 'Paid',
  },
  {
    id: 8,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Real Estate',
    status: 'Paid',
  },
  {
    id: 9,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Adjudicated/Active',
    status: 'Paid',
  },
  {
    id: 10,
    year: '2020',
    taxNotice: '419499',
    taxPayerName: 'Johnson, Ashley R',
    taxPayerAddress: '10032 Lexingtone DR',
    ward: '001',
    balanceDue: '$250',
    parcelType: 'Adjudicated/Active',
    status: 'Paid',
  },
];
